name: build and deploy
on:
  push:
  workflow_dispatch:
jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: |
          cd src
          yarn install
          yarn build
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+action@github.com>"
